fragment Track on TrackEntity {
  id
  attributes {
    name
    duration
    playCount
    audio {
      data {
        attributes {
          name
          url
        }
      }
    }
    album {
      data {
        id
        attributes {
          name
          releaseDate
          cover {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
    artist {
      data {
        id
        attributes {
          name
        }
      }
    }
  }
}
