query AlbumList {
  albums {
    data {
      id
      attributes {
        name
        cover {
          data {
            attributes {
              url
            }
          }
        }
        artist {
          data {
            id
            attributes {
              name
            }
          }
        }
      }
    }
  }
}
