mutation ChangePassword($currentPassword: String!, $password: String!, $passwordConfirmation: String!) {
  changePassword(password: $password, currentPassword: $currentPassword, passwordConfirmation: $passwordConfirmation) {
    __typename
  }
}
