mutation ResetPassword($code: String!, $password: String!, $passwordConfirmation: String!) {
  resetPassword(code: $code, password: $password, passwordConfirmation: $passwordConfirmation) {
    __typename
    user {
      email
    }
  }
}
