query Artist($id: ID!) {
  artist(id: $id) {
    data {
      id
      attributes {
        name
        albums {
          data {
            ...Album
          }
        }
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }

  popularTracks: tracks(filters: { artist: { id: { eq: $id } } }, sort: "playCount:desc") {
    data {
      ...Track
    }
  }
}
