query GetArtistAlbums($artistId: ID!) {
  artist(id: $artistId) {
    data {
      attributes {
        albums {
          data {
            ...AlbumPreview
          }
        }
      }
    }
  }
}
